/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CarFeature } from "./CarFeature";
import { CarFeatureCountArgs } from "./CarFeatureCountArgs";
import { CarFeatureFindManyArgs } from "./CarFeatureFindManyArgs";
import { CarFeatureFindUniqueArgs } from "./CarFeatureFindUniqueArgs";
import { DeleteCarFeatureArgs } from "./DeleteCarFeatureArgs";
import { CarFeatureService } from "../carFeature.service";
@graphql.Resolver(() => CarFeature)
export class CarFeatureResolverBase {
  constructor(protected readonly service: CarFeatureService) {}

  async _carFeaturesMeta(
    @graphql.Args() args: CarFeatureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CarFeature])
  async carFeatures(
    @graphql.Args() args: CarFeatureFindManyArgs
  ): Promise<CarFeature[]> {
    return this.service.carFeatures(args);
  }

  @graphql.Query(() => CarFeature, { nullable: true })
  async carFeature(
    @graphql.Args() args: CarFeatureFindUniqueArgs
  ): Promise<CarFeature | null> {
    const result = await this.service.carFeature(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CarFeature)
  async deleteCarFeature(
    @graphql.Args() args: DeleteCarFeatureArgs
  ): Promise<CarFeature | null> {
    try {
      return await this.service.deleteCarFeature(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
