/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VariantService } from "../variant.service";
import { VariantCreateInput } from "./VariantCreateInput";
import { Variant } from "./Variant";
import { VariantFindManyArgs } from "./VariantFindManyArgs";
import { VariantWhereUniqueInput } from "./VariantWhereUniqueInput";
import { VariantUpdateInput } from "./VariantUpdateInput";
import { CarReviewFindManyArgs } from "../../carReview/base/CarReviewFindManyArgs";
import { CarReview } from "../../carReview/base/CarReview";
import { CarReviewWhereUniqueInput } from "../../carReview/base/CarReviewWhereUniqueInput";
import { CarSpecificationFindManyArgs } from "../../carSpecification/base/CarSpecificationFindManyArgs";
import { CarSpecification } from "../../carSpecification/base/CarSpecification";
import { CarSpecificationWhereUniqueInput } from "../../carSpecification/base/CarSpecificationWhereUniqueInput";

export class VariantControllerBase {
  constructor(protected readonly service: VariantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Variant })
  async createVariant(
    @common.Body() data: VariantCreateInput
  ): Promise<Variant> {
    return await this.service.createVariant({
      data: {
        ...data,

        model: data.model
          ? {
              connect: data.model,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fuelType: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Variant] })
  @ApiNestedQuery(VariantFindManyArgs)
  async variants(@common.Req() request: Request): Promise<Variant[]> {
    const args = plainToClass(VariantFindManyArgs, request.query);
    return this.service.variants({
      ...args,
      select: {
        createdAt: true,
        fuelType: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Variant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async variant(
    @common.Param() params: VariantWhereUniqueInput
  ): Promise<Variant | null> {
    const result = await this.service.variant({
      where: params,
      select: {
        createdAt: true,
        fuelType: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        name: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Variant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVariant(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() data: VariantUpdateInput
  ): Promise<Variant | null> {
    try {
      return await this.service.updateVariant({
        where: params,
        data: {
          ...data,

          model: data.model
            ? {
                connect: data.model,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fuelType: true,
          id: true,

          model: {
            select: {
              id: true,
            },
          },

          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Variant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVariant(
    @common.Param() params: VariantWhereUniqueInput
  ): Promise<Variant | null> {
    try {
      return await this.service.deleteVariant({
        where: params,
        select: {
          createdAt: true,
          fuelType: true,
          id: true,

          model: {
            select: {
              id: true,
            },
          },

          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/carReviews")
  @ApiNestedQuery(CarReviewFindManyArgs)
  async findCarReviews(
    @common.Req() request: Request,
    @common.Param() params: VariantWhereUniqueInput
  ): Promise<CarReview[]> {
    const query = plainToClass(CarReviewFindManyArgs, request.query);
    const results = await this.service.findCarReviews(params.id, {
      ...query,
      select: {
        comment: true,
        createdAt: true,
        id: true,
        rating: true,
        updatedAt: true,
        user: true,

        variant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/carReviews")
  async connectCarReviews(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carReviews: {
        connect: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/carReviews")
  async updateCarReviews(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carReviews: {
        set: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/carReviews")
  async disconnectCarReviews(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carReviews: {
        disconnect: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/carSpecifications")
  @ApiNestedQuery(CarSpecificationFindManyArgs)
  async findCarSpecifications(
    @common.Req() request: Request,
    @common.Param() params: VariantWhereUniqueInput
  ): Promise<CarSpecification[]> {
    const query = plainToClass(CarSpecificationFindManyArgs, request.query);
    const results = await this.service.findCarSpecifications(params.id, {
      ...query,
      select: {
        createdAt: true,
        feature: true,
        id: true,
        updatedAt: true,
        value: true,

        variant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/carSpecifications")
  async connectCarSpecifications(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarSpecificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carSpecifications: {
        connect: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/carSpecifications")
  async updateCarSpecifications(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarSpecificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carSpecifications: {
        set: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/carSpecifications")
  async disconnectCarSpecifications(
    @common.Param() params: VariantWhereUniqueInput,
    @common.Body() body: CarSpecificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carSpecifications: {
        disconnect: body,
      },
    };
    await this.service.updateVariant({
      where: params,
      data,
      select: { id: true },
    });
  }
}
